import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import erpEmployees from "./erp-employees.js";
import erpInvoices from "./erp-invoices.js";
import erpTrips from "./erp-trips.js";
import erpExpenses from "./erp-expenses.js";
import erpOperations from "./erp-operations.js";
import authRouter from "./auth.js";
import productsRouter from "./products.js";
import ordersWorkflow from "./orders-workflow.js";
import customersPortal from "./customers-portal.js";
import statsRouter from "./stats.js";
import googleSheetsRouter from "./google-sheets.js";
import warehousesRouter from "./warehouses.js";
import tariffsRouter from "./tariffs.js";
import companyBranchDocumentsRouter from "./company-branch-documents.js";
import driverExpensesRouter from "./driver-expenses.js";
import driversRouter from "./drivers.js";
import aiRouter from "./ai.js";
import workshopRouter from "./workshop.js";
import externalRentalsRouter from "./external-rentals.js";
import offersRouter from "./offers.js";
import rentalVehicleTypesRouter from "./rental-vehicle-types.js";
import driverBonusRouter from "./driver-bonus.js";
import vehicleManagementRouter from "./vehicle-management.js";
import legalRouter from "./legal.js";
import clientLocationsRouter from "./client-locations.js";
import loadingPointsRouter from "./loading-points.js";
import orderRatingsRouter from "./order-ratings.js";
import repRouter from "./rep.js";
import trailerConfigsRouter from "./trailer-configs.js";
import supplyRequestsRouter from "./supply-requests.js";
import supervisorSettingsRouter from "./supervisor-settings.js";
import driverSettlementsRouter from "./driver-settlements.js";
import auditorRouter from "./auditor.js";
import gpsRouter from "./gps.js";
import vehicleTypeDefsRouter from "./vehicle-type-defs.js";
import bulkerMovementsRouter from "./bulker-movements.js";
import internalRequestsRouter from "./internal-requests.js";
import factoryOrdersRouter from "./factory-orders.js";
import driverDocRequestsRouter from "./driver-doc-requests.js";
import teidaratRouter from "./teidarat.js";
import repRequestsRouter from "./rep-requests.js";
import loadingOrdersRouter from "./loading-orders.js";
import bulkerVehiclesRouter from "./bulker-vehicles.js";
import unloadLocationsRouter from "./unload-locations.js";
import storageRouter from "./storage.js";
import systemBackupRouter from "./system-backup.js";
import { isSystemRestoreActive, trackApiRequest } from "../lib/system-restore-state.js";
import routingDispatchRouter from "./routing-dispatch.js";
import excelImportRouter from "./excel-import.js";
import adminRouter from "./admin.js";
import devDashboardRouter from "./dev-dashboard.js";
import journalEntriesRouter from "./journal-entries.js";
import mkghRouter from "./mkgh.js";
import driverCustodyRouter from "./driver-custody.js";
import invoiceExtractionRouter from "./invoice-extraction.js";
import rentalAccountsRouter from "./rental-accounts.js";
import rentalTripPortalRouter from "./rental-trip-portal.js";
import chatRouter from "./chat.js";

const router: IRouter = Router();

router.use((req, res, next) => {
  if (isSystemRestoreActive()) {
    if (req.path === "/health" || req.path === "/health/") return next();
    return res.status(503).json({ error: "تجري استعادة نسخة النظام؛ حاول بعد انتهائها" });
  }
  const release = trackApiRequest();
  res.once("finish", release);
  res.once("close", release);
  next();
});

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(ordersWorkflow);
router.use(customersPortal);
router.use(statsRouter);
router.use(googleSheetsRouter);
router.use(warehousesRouter);
router.use(tariffsRouter);
router.use(companyBranchDocumentsRouter);
router.use(driverExpensesRouter);
router.use(driversRouter);
router.use(erpEmployees);
router.use(erpInvoices);
router.use(erpTrips);
router.use(erpExpenses);
router.use(erpOperations);
router.use(workshopRouter);
router.use(aiRouter);
router.use(externalRentalsRouter);
router.use(offersRouter);
router.use(rentalVehicleTypesRouter);
router.use(driverBonusRouter);
router.use(vehicleManagementRouter);
router.use(legalRouter);
router.use(clientLocationsRouter);
router.use(loadingPointsRouter);
router.use(orderRatingsRouter);
router.use(repRouter);
router.use(trailerConfigsRouter);
router.use(supplyRequestsRouter);
router.use(supervisorSettingsRouter);
router.use(driverSettlementsRouter);
router.use(auditorRouter);
router.use(gpsRouter);
router.use(vehicleTypeDefsRouter);
router.use(bulkerMovementsRouter);
router.use(internalRequestsRouter);
router.use(factoryOrdersRouter);
router.use(driverDocRequestsRouter);
router.use(teidaratRouter);
router.use(repRequestsRouter);
router.use(loadingOrdersRouter);
router.use(bulkerVehiclesRouter);
router.use(unloadLocationsRouter);
router.use(storageRouter);
router.use(systemBackupRouter);
router.use(routingDispatchRouter);
router.use(excelImportRouter);
router.use(adminRouter);
router.use(devDashboardRouter);
router.use(journalEntriesRouter);
router.use(mkghRouter);
router.use(driverCustodyRouter);
router.use(rentalAccountsRouter);
router.use(rentalTripPortalRouter);
router.use(chatRouter);
router.use(invoiceExtractionRouter);

export default router;
